language: python

python: "3.7"

git:
  depth: 1

install:
  - pip install -r requirements.txt

before_script:
   - echo "DEBUG = False" >> .env
   - echo "SECRET_KEY = $ SECRET_KEY" >> .env

script:
  - cd mysite
  - python manage.py test
