language: python

python: "3.7"

git:
  depth: 1

env:
  - DEBUG="True"
  - TEMPLATE_DEBUG="True"
  - SECRET_KEY="secretkey"
  - DATABASE_URL="mysql://myuser:mypassword@myhost/mydatabase"

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install Django
  - pip install decouple

script:
  - cd mysite
  - python manage.py test
