language: python

python: "3.7"

git:
  depth: 1

install:
  - pip install -r requirements.txt

before_script:
   - echo "DEBUG = False" >> .env
   - echo "SECRET_KEY = secretkeys" >> .env

script:
  - coverage run manage.py test

after_script:
  - bash <(curl -s https://codecov.io/bash)