# Generated by Django 3.1 on 2020-11-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='prev_vote',
            field=models.CharField(default='', max_length=200),
        ),
    ]
