# Generated by Django 3.1 on 2020-11-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_prev_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='prev_vote',
        ),
        migrations.AddField(
            model_name='question',
            name='prev_choice',
            field=models.CharField(default='', max_length=200),
        ),
    ]
