# Generated by Django 3.1 on 2020-11-01 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20201101_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='prev_choice',
            new_name='prev_vote',
        ),
    ]
